name: 'Match Angular Versions'
description: 'Modifies the package.json with matching dependency versions for a given base Angular version'
author: 'GitHub'
inputs:
  angular-version:
    description: 'The base Angular version used to match the dependency versions'
    required: true
  root-path:
    description: 'Path to the root folder containing the package.json and angular.json'
    required: false
    default: './'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'gray-dark'
