name: 'Match Angular Versions'
description: 'Modifies the package.json with matching dependency versions for a given base Angular version'
author: 'ngworker'
inputs:
  angular-version:
    description: 'The base Angular version used to match the dependency versions'
    required: true
  root-folder-path:
    description: 'Path of your project folder where your package.json file lives. Relative to your repository root'
    required: false
    default: '.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'gray-dark'
